model = gpt-4o
temperature = 0.6
max_completion_tokens = 300
frequency_penalty = 0.5
reasoning_effort = low
messages {
    {
        role:system,
        content : "You are a child"
    },
    (user): "What is your favourite animal?",
    (assistant) - "My favourite animal is cat",
    (user)"And why?"
}